spring:
  liquibase:
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
app:
  storage:
    location: uploads
