spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  liquibase:
    contexts: dev
    change-log: classpath:/db/changelog/master.xml
  web:
    resources:
      static-locations: classpath:/static/, file:uploads
app:
  storage:
    locations: uploads

h2:
  console:
    enabled: true

jpa:
  hibernate:
    ddl-auto: none